project:
  name: quickstart-darktrace-vsensor
  owner: quickstart-eng@amazon.com
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: quickstart-darktrace-vsensor
    BastionKeyPairName: "key-pair-name"
    AvailabilityZones: $[taskcat_getaz_2]
    RemoteAccessCIDR: "127.0.0.1/32"
    VSensorMasterHostname: "https://example.com"
    VSensorMasterPushtoken: "FakePushToken"
    VSensorUpdatekey: "XXXXXXXXX:XXXXXXXX"
    VSensorKeyPairName: "key-pair-name"
  template: ./templates/darktrace-vsensor-new-vpc.template.yaml
tests:
  vsensor:
    regions:
      - eu-west-1
  vsensor-all-regions:
    regions:
      - af-south-1
      - ap-east-1
      - ap-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-south-1
      - eu-north-1
      - me-south-1
      - sa-east-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2

    
