// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Post deployment steps

=== Configure networking

If your Darktrace appliance is behind a firewall, you must grant access to the appliance to the IP addresses of your NAT gateways. For a new VPC deployment, use the Elastic IPs of the NAT gateway on the *Outputs* tab of the stack in the https://console.aws.amazon.com/cloudfront/home?[AWS CloudFormation console]. For an existing VPC deployment, use the IP addresses of the existing NAT gateways.
TODO: I don't see *NAT Gateway Elastic IPs* in cfn_outputs.png. I don't need a new screen shot, just confirm that if I say "For a new VPC deployment, use the Elastic IPs of the NAT gateway on the *Outputs* tab of the stack in the AWS CloudFormation console," this is correct.

=== Configure traffic mirroring

VPC Traffic Mirroring is only supported on AWS Nitro-based EC2 instance types and some non-Nitro instance types. For more information, see https://aws.amazon.com/about-aws/whats-new/2021/02/amazon-vpc-traffic-mirroring-supported-select-non-nitro-instance-types[Amazon VPC Traffic Mirroring is now supported on select non-Nitro instance types]. 

To monitor EC2 instance types that do not support VPC Traffic Mirroring, configure them with Darktrace osSensors. When doing this, use the DNS name of the Network Load Balancer on the *Outputs* tab of the stack in the https://console.aws.amazon.com/cloudfront/home?[CloudFormation console]. For more information about configuring osSensors, visit the https://customerportal.darktrace.com/login[Darktrace Customer Portal].

To add your existing EC2 instances to be mirrored and monitored, configure a traffic mirror session. For more information, see https://docs.aws.amazon.com/vpc/latest/mirroring/traffic-mirroring-session.html[Traffic mirror sessions]. When doing this, use the traffic mirror target and filter IDs on the *Outputs* tab of the stack in the https://console.aws.amazon.com/cloudfront/home?[AWS CloudFormation console]. You can automate the process of adding your existing EC2 instances to this deployment. For more information, contact your Darktrace representative for scripts and guidance to do this.

=== Test the deployment

This Quick Start should only complete successfully if the parameters fit the correct format and the *Update Key* and *Push Token* are valid.

Once the deployment has completed, the Master UI _System Config_ / _Push Tokens_ section should display the expected number of probes connected.

Once EC2 Instances have been configured for Traffic Mirroring above, these instances should appear inside the Threat Visualiser.


== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

=== Network Security
The default network security setup of this solution follows AWS security best practices. The provisioned {partner-product-name} instances are deployed in private subnets and can only be accessed via SSH via the Bastion.

For existing VPC deployments, it is important for the *Security Groups* defined by the customer allow only required access for SSH from trusted sources. It is not recommended to allow direct SSH access to vSensors from the internet.

=== OS Security

To gain root access to your vSensor instances you may use `ubuntu` user and then sudo to root. The key-pair provided during deployment will be required to access the `ec2-user` of the Bastion and `ubuntu` user of vSensors.

Deployed Bastions are set to automatically update. 
The deployed vSensors are configured to update daily from the {partner-company-name} and Ubuntu package repositories for the latest security and product updates.

===== AWS Services

- AWS CloudFormation

* Documentation: https://aws.amazon.com/documentation/cloudformation/

* Helper scripts: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html

- Amazon EC2 user guide for Linux https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/

- Amazon S3 https://aws.amazon.com/documentation/s3/

- Amazon VPC https://aws.amazon.com/documentation/vpc/

===== Darktrace

- Darktrace https://darktrace.com

- Darktrace Customer Portal https://customerportal.darktrace.com

- Darktrace Customer Portal vSensor Guides https://customerportal.darktrace.com/product-guides/main/vsensor-introduction
