// If no preperation is required, remove all content from here

==== Prepare your Darktrace Deployment

The vSensor deployment will use *Push Token Mode* to connect back to the Master Appliance. Be prepared to allow network access from your existing Master Appliance to your new vSensor deployment. This may require firewall configurations.

NOTE: *Darktrace Cloud Masters* are already configured to allow this access.

You will need to register a new *Push Token* to connect the vSensors to the Master. All vSensors in this Deployment will share this token.

    * Log into the Darktrace Master instance UI and navigate to the _System Config_ page from the main menu. Locate the _Push Probe Tokens_ section.

    * Enter a label for the vSensor Deployment and click _Add_ - a token will generate in the form of _[label:string]_. This token will be shown only once, please note it down for the deployment.

    * The vSensor label is part of the token - to change the label, the token must be fully regenerated.