// If no preperation is required, remove all content from here

==== Prepare your Darktrace Deployment

Register a new push token to enable connection between vSensor probes and an existing Darktrace appliance. All of the vSensor instances in this deployment share the same push token.
NOTE: Darktrace cloud instances are already configured to allow push token access.

. Log into the Darktrace appliance user interface.
. Choose the *System Config* page from the main menu.
. In the *Push Probe Tokens* section, enter a label for the vSensor Deployment. To change the vSensor label later, you must redo the steps to generate a new token.
. Choose *Add*. A token is generated in the form of `[label:string]`. 
. Record the token, as it only displays once. You must enter the token in the *Appliance push token* parameter field during Quick Start deployment.

If your Darktrace appliance is behind a firewall, you must grant access to the appliance to the IP addresses of your NAT gateways after deployment. For more information, see link:#post-deployment-steps[Post deployment steps], later in this guide.


