//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

=== Generate AWS Systems Manager parameters

The Quick Start now uses AWS Systems Manager Parameter Store to hold the configuration and secrets for Darktrace vSensor. This is due to EC2 instance user data being https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html[unencrypted^].

https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-su-create.html[Create^] separate "Secure String" SSM Parameters in the expected AWS region for each of the following:

. vSensor Update Key (e.g. `abcdefg:12345678`)
. Master Instance Hostname (e.g. `https://mastername.cloud.darktrace.com:443`)
. Master Instance Push Token (e.g. `vsensor-push-token:123456abcdefg`)
. Master Instance Proxy (e.g. `http://proxyname.example.com:3128`, `http://username@password:proxyname.example.com:3128` or `none` to not use a proxy)
. osSensor HMAC (e.g. `ossensorhmac123456abcdefg` or `none` to disable osSensor support)

You will provide the parameter names to the CloudFormation template, for the vSensor to automatically decrypt these values on start up.

Using SSM parameters provides the benefit that configurations can be more easily cycled out using the Auto Scaling Group Instance Refresh features, without having to redeploy the Quick Start template.

NOTE: Please review https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html[ASG Instance Refresh Documentation]. Refreshing all instances will cause an outage, since instances are terminated before new instances are created.

=== Register a push token

Register a new push token to enable connection between vSensor probes and an existing Darktrace on-premise or cloud appliance. All of the vSensor instances in this deployment share the same push token.

. Log into the Darktrace console.
. On the main menu, choose *Admin > System Config*.
. In the *Push Probe Tokens* section, enter a label for the vSensor deployment.
. Choose *Add*. A token is generated in the form of `[label:string]`. 
. Record the token, as it only displays once. You must enter the token in the *Appliance push token* link:#_parameter_reference[parameter] field during Quick Start deployment.

If your Darktrace appliance is behind a firewall, you must grant access to the appliance to the IP addresses of your NAT Gateways after deployment. For more information, see link:#post-deployment-steps[Post deployment steps], later in this guide.

NOTE: Darktrace cloud appliances are already configured to allow push token access, no firewall changes are necessary.
